sudo: true
dist: trusty 
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- openssl aes-256-cbc -K $encrypted_f42060fe945a_key -iv $encrypted_f42060fe945a_iv -in assets/server.key.enc -out assets/server.key -d
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH

before_script:
- export USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300

script:
- export SFDX_AUTOUPDATE_DISABLE=true
- sfdx plugins:install salesforcedx@pre-release
- sfdx plugins
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
- sfdx plugins
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p